const AppConfig = {
	EVENTS: {
		RECEIVED_USER_INFO : "RECEIVED_USER_INFO",
		NORMAL_UPVOTE: "NORMAL_UPVOTE",
		ACCEPTED_UPVOTE: "ACCEPTED_UPVOTE",
		SUBMIT_ANSWER: "SUBMIT_ANSWER",
		REQUEST_BE_STATISTICS: "REQUEST_BE_STATISTICS",
		RECEIVED_BE_STATISTICS: "RECEIVED_BE_STATISTICS"
	}
};
