const SE = new SEController(13513, '9)bOO0dxebBgnNxZafI7Tg((');

const AppConfig = {
	EVENTS: {
		POST_ANSWER_WRITE_SUCCES: "POST_ANSWER_WRITE_SUCCES",
		UPVOTE_WRITE_SUCCES: "UPVOTE_WRITE_SUCCES",
		NO_SITE_ACCOUNT: "NO_SITE_ACCOUNT",
		ON_ERROR: "ON_ERROR",
		RECEIVED_BASE_STATISTICS: "RECEIVED_BASE_STATISTICS",
		RECEIVED_TAGS_STATISTICS: "RECEIVED_TAGS_STATISTICS",
		RECEIVED_ANSWERS_STATISTICS: "RECEIVED_ANSWERS_STATISTICS",
		RECEIVED_TOP_TAGS_STATISTICS: "RECEIVED_TOP_TAGS_STATISTICS",
		RECEIVED_USER_INFO: "RECEIVED_USER_INFO",
		RECEIVED_QUESTIONS: "RECEIVED_QUESTIONS",
		RECEIVED_ANSWERS: "RECEIVED_ANSWERS",
		SUBMIT_ANSWER: "SUBMIT_ANSWER",
		REQUEST_BE_STATISTICS: "REQUEST_BE_STATISTICS",
		RECEIVED_BE_STATISTICS: "RECEIVED_BE_STATISTICS"
	}
};